In [5]:
import numpy as np

In [4]:
# 1. Convert List to 1D Array
# Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.

# Expected Output:

# Original List: [12.23, 13.32, 100, 36.32] One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]
ls = [12.23, 13.32, 100, 36.32]
arr = np.array(ls)
print(arr)


[ 12.23  13.32 100.    36.32]


In [9]:
# 2. Create 3x3 Matrix (2?10)
# Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

# Expected Output:

# [[ 2 3 4] [ 5 6 7] [ 8 9 10]]

Z = np.arange(2, 11).reshape((3,3))
print(Z)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [10]:
# 3. Null Vector (10) & Update Sixth Value
# Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.

# [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

# Update sixth value to 11 [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

Z = np.zeros(10)
Z[6] = 11
print(Z)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [11]:
# 4. Array from 12 to 38
# Write a NumPy program to create an array with values ranging from 12 to 38.

# Expected Output:

# [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

Z = np.arange(12, 38, dtype=int)
print(Z)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [12]:
# 5. Convert Array to Float Type
# Write a NumPy program to convert an array to a floating type.

# Sample output:

# Original array [1, 2, 3, 4]
arr = np.array([1, 2, 3, 4])
arr = arr.astype(float)
print(arr)

[1. 2. 3. 4.]


In [19]:
# 6. Celsius to Fahrenheit Conversion
# Write a NumPy program to convert Centigrade degrees into Fahrenheit degrees. Centigrade values are stored in a NumPy array.

# Sample Array [0, 12, 45.21, 34, 99.91, 32] [-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]

# Expected Output:

# Values in Fahrenheit degrees: [ 0. 12. 45.21 34. 99.91 32. ]

# Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

# Values in Centigrade degrees: [-17.78 -11.11 7.34 1.11 37.73 0. ]

# Values in Fahrenheit degrees: [-0. 12. 45.21 34. 99.91 32. ]

A = np.array([0, 12, 45.21, 34, 99.91, 32])
B = np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])

Fahrenheit = A * 9 / 5 + 32
print(f"Fahrenheit: {Fahrenheit}")
print(f"Centigrade: {A}")
Fahrenheit2 = B * 9 / 5 + 32
print(f"Fahrenheit: {Fahrenheit2}")
print(f"Centigrade: {B}")




Fahrenheit: [ 32.     53.6   113.378  93.2   211.838  89.6  ]
Centigrade: [ 0.   12.   45.21 34.   99.91 32.  ]
Fahrenheit: [-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]
Centigrade: [-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [20]:
# 7. Append Values to Array (Do self-tudy)
# Write a NumPy program to append values to the end of an array.

# Expected Output:

# Original array: [10, 20, 30]

# After append values to the end of the array: [10 20 30 40 50 60 70 80 90]
arr = np.array([10, 20, 30])
newarr = np.array([40, 50, 60, 70, 80, 90])
Z = np.append(arr,newarr)
print(Z)

[10 20 30 40 50 60 70 80 90]


In [25]:
# 8. Array Statistical Functions (Do self-tudy)
# Create a random NumPy array of 10 elements and calculate the mean, median, and standard deviation of the array.
arr = np.array(np.random.randint(0, 100, size=10))
print(f"Array: {arr}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")
print(f"Standard deviation: {np.std(arr)}")



Array: [47 57  9 94 61 94 87 39 81 56]
Mean: 62.5
Median: 59.0
Standard deviation: 25.800193797721754


In [28]:
# 9 Find min and max
# Create a 10x10 array with random values and find the minimum and maximum values.
Z = np.random.randint(1, 100, size=(10,10))
print(f"Array: {Z}")
print(f"Max_value: {np.max(Z)}")
print(f"Min_value: {np.min(Z)}")

Array: [[87 49 56  7 83 92 99  3 67  3]
 [96 90 30 56 33 75 21 22 28 37]
 [65 71  9 46 46 46 39 93 70 73]
 [25 27 57 14 80 68 52 43 31 85]
 [38 92 32  8 36 47  5 53 88 41]
 [82 30 80 37 13  3 47  6 29 48]
 [89 17 87 83 85 12 69 24 38 52]
 [94 62 30 27 43 54 92 10 13 60]
 [ 3 98  3 61 93 18 90 55 40 60]
 [43 26 32 46 98  4 63 49 81 44]]
Max_value: 99
Min_value: 3


In [30]:
# 10
# Create a 3x3x3 array with random values.
Z = np.random.randint(1,100, size=(3,3,3))
print(Z)
arr = np.random.random((3,3,3))
print(arr)

[[[43 22 77]
  [27 74 99]
  [30 91 54]]

 [[73 71 39]
  [25 80 91]
  [73 80 18]]

 [[74 60 76]
  [75 25 91]
  [72 72 86]]]
[[[0.69977325 0.32999523 0.65864555]
  [0.2463434  0.37069243 0.65818276]
  [0.68594562 0.30073318 0.89410652]]

 [[0.30868464 0.13055829 0.85659084]
  [0.14189261 0.28784849 0.26542426]
  [0.96191145 0.567372   0.10116281]]

 [[0.72047626 0.23206373 0.91937441]
  [0.46943736 0.2130048  0.05790481]
  [0.24675856 0.5367992  0.97963994]]]
